server:
  port: 8092
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  application:
    name: "appldev"
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**


